# Generated by Django 3.0.4 on 2020-04-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='id_namme',
            new_name='id_name',
        ),
    ]
