# Generated by Django 3.0.4 on 2020-04-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_co_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='gender',
            new_name='Ranks',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='id_name',
            new_name='id_num',
        ),
    ]
